### ISSUE TITLE
Add compatibility to ParrotOS

### ISSUE THREAD

**Issue by R3n0x** [Tylous/SniffAir#24]
Hello,

When I'm going to install SniffAir it tells me that the distribution is unknown... 

The system is **Parrot OS** 4.3

[](https://www.parrotsec.org/download.php)

Could you add compatibility with it ?

Thank you very much in advance.

**Comment by n3xuzZ** [comment]
hey you can try to edit the setup.sh file and change debian to parrot os. For me it had worked with blackarch !
