### ISSUE TITLE
Freeradius.com domain expired

### ISSUE THREAD

**Issue by g3ksmithington** [Tylous/SniffAir#25]
Tried to install SniffAir this afternoon, but got the following while running the setup.sh script:

--2018-11-15 14:25:14--  ftp://ftp.freeradius.org/pub/radius/old/freeradius-server-2.1.12.tar.bz2
           => ‘freeradius-server-2.1.12.tar.bz2’
Resolving ftp.freeradius.org (ftp.freeradius.org)... 62.210.29.29
Connecting to ftp.freeradius.org (ftp.freeradius.org)|62.210.29.29|:21... failed: Connection timed out.
Retrying.

Turns out the domain expired:
![image](https://user-images.githubusercontent.com/854881/48576581-ea8a8680-e8e2-11e8-8902-0f5c11452467.png)

I'm currently using a mirror located here: https://ftp.yz.yamagata-u.ac.jp/pub/network/freeradius/old/freeradius-server-2.1.12.tar.bz2, but that comes with another whole other host of potential problems

**Comment by haxorthematrix** [comment]
freeradius.org as indicated in the command output, versus freeradius.com in the "advertisement" are not the same (.org, .com).  I did an install yesterday and tested ftp://ftp.freeradius.org and is working just fine from my location.
