### ISSUE TITLE
does evil twin works as this ?

### ISSUE THREAD

**Issue by minanagehsalalma** [Tylous/SniffAir#27]
[+] Evil Twin - Creates a Fake Access Point, Clients Connect to Divulging MSCHAP Hashes or Cleartext Passwords

[Stealing 802.1x Credentials with Rogue AP & RADIUS server](https://www.youtube.com/watch?v=HoihKhQWZ7)

**Comment by Tylous** [comment]
The youtube link is broken. But please check out https://m.youtube.com/watch?v=AeqfYGbHwWw

**Comment by minanagehsalalma** [comment]
@Tylous  
i don't know what broke it ...
but here is it 
https://youtu.be/HoihKhQWZ7k

**Comment by minanagehsalalma** [comment]
@Tylous  
https://youtu.be/AeqfYGbHwWw?t=2243

but this works on ios only ? as android needs to set the configuration (GTC) manually !

**Comment by Tylous** [comment]
No it works on Android as well.
