### ISSUE TITLE
Connected Device Not Opening Captive Portal

### ISSUE THREAD

**Issue by jepunband** [Tylous/SniffAir#29]
Hi , upon launching the tool, i connected the device to the wifi .. it launches the browser, but the captive portal page is not displaying on the device. How do i solve this ?

=====================
 Module: Captive Portal
 Interface: wlan1          The Interface to Use
 SSID: test         The SSID to Masquerade As
 Channel: 4          The Channel for the AP to be on
 Template: Cisco (More to be added soon)
 >>  [captive][Captive Portal]# run
Setting up Hostapd configuration
Setting up DNS
Launching web server

10.20.0.201 - - [30/Oct/2019 00:47:43] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:47:43] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:47:43] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:47:43] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:47:44] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:48:13] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:48:15] "GET /connect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:48:15] "GET /connect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:48:15] "GET /connect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [30/Oct/2019 00:48:15] "GET /connect HTTP/1.1" 200 -

**Comment by Tylous** [comment]
Hello, I am going to need more information. Have you tried manually going to the IP of the captive portal to see if it was actually spun up properly? Is the DNS server running or bugging out?

**Comment by jepunband** [comment]
hi,

1. IP adress of wlan1 is 10.0.20.1  ( going to this ip on a connected android device opens up the captive page )
2. IP on the connected device is 10.0.20.201
3.  DNS info :
$nmcli device show eth0 | grep IP4.DNS
IP4.DNS[1]:                             192.168.1.1
$nmcli device show wlan1 | grep IP4.DNS


Launching web server
10.20.0.201 - - [31/Oct/2019 11:05:56] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:00] "GET /connect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:00] "GET /connect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:01] "GET /connect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:01] "GET /connect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:06] "GET /generate_204 HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:07] "GET /qq_product_operations/nettest/index2.html?r=26737&mType=netdetect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:07] "GET /qq_product_operations/nettest/index.html?r=96235&mType=netdetect HTTP/1.1" 200 -
./login.html
################################################################################################################
MAC ADDRESS: 60:8f:5c:ea:e9:b2, USERNAME: None, PASSWORD: None
################################################################################################################
10.20.0.201 - - [31/Oct/2019 11:06:08] "POST /configsvr/openlist.jsp HTTP/1.1" 200 -
10.20.0.201 - - [31/Oct/2019 11:06:14] "GET /qq_product_operations/nettest/index.html?r=92825&mType=netdetect HTTP/1.1" 200 -
./login.html
10.20.0.201 - - [31/Oct/2019 11:06:14] "GET /qq_product_operations/nettest/index2.html?r=451&mType=netdetect HTTP/1.1" 200 -
./login.html

**Comment by Tylous** [comment]
It does not look like the DNS server config generated by SniffAir is running. When you run it, in the modules captive portal folder there should be a dns.log file please review that and let me know what it says.
