### ISSUE TITLE
Recreate setup.py

### ISSUE THREAD

**Issue by tufter** [Tylous/SniffAir#3]
The current setup.py is bad, including os.system with apt-get specifically and cloning a repository from bitbucket.

**Comment by CodeBrauer** [comment]
Also a recommended/required python version would be important, for users that don't know much about python.

**Comment by guedou** [comment]
You should use https://github.com/secdev/scapy =)
We don't support the version on bitbucket anymore.

**Comment by Tylous** [comment]
Thank you for the information, we are in the process of updating the setup.py script. We'll have an updated version shortly.

**Comment by Tylous** [comment]
A new setup script has been release in v1.1
