### ISSUE TITLE
nmcli error

### ISSUE THREAD

**Issue by jepunband** [Tylous/SniffAir#35]
hi trying to get sniffair to work in kali nethunter, but i'm getting error  ...

 >>  [cp][Captive Portal]# run
Error: Could not create NMClient object: Could not connect: No such file or directory.
Error: Could not create NMClient object: Could not connect: No such file or directory.
Setting up Hostapd configuration
Setting up DNS
Launching web server

**Comment by Tylous** [comment]
It appears to be a looking for nmclient which I don’t think is install on nethunter.

**Comment by Tylous** [comment]
Closing
